package com.lostandfound.activities;

import android.content.Intent;
import android.os.Bundle;
import android.text.SpannableString;
import android.text.Spanned;
import android.text.style.ForegroundColorSpan;
import android.text.style.UnderlineSpan;
import android.util.Log;
import android.view.View;

import androidx.annotation.Nullable;
import androidx.appcompat.app.AppCompatActivity;
import androidx.core.content.ContextCompat;

import com.google.android.gms.auth.api.signin.GoogleSignIn;
import com.google.android.gms.auth.api.signin.GoogleSignInAccount;
import com.google.android.gms.auth.api.signin.GoogleSignInClient;
import com.google.android.gms.auth.api.signin.GoogleSignInOptions;
import com.google.android.gms.common.api.ApiException;
import com.google.android.gms.tasks.Task;
import com.google.android.material.dialog.MaterialAlertDialogBuilder;
import com.google.android.material.snackbar.Snackbar;
import com.google.firebase.auth.AuthCredential;
import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.auth.GoogleAuthProvider;
import com.lostandfound.R;
import com.lostandfound.databinding.ActivityLoginBinding;
import com.lostandfound.utils.FirebaseHelper;
import com.lostandfound.utils.ValidationUtils;

/**
 * Login screen. Uses FirebaseAuth email/password and Google sign-in.
 */
public class LoginActivity extends AppCompatActivity {

    private static final String TAG = "LoginActivity";
    private static final int RC_SIGN_IN = 9001;

    private ActivityLoginBinding binding;
    private FirebaseAuth auth;
    private GoogleSignInClient googleSignInClient;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        binding = ActivityLoginBinding.inflate(getLayoutInflater());
        setContentView(binding.getRoot());

        auth = FirebaseHelper.getInstance().getAuth();
        setupGoogleSignIn();

        styleSignUpLink();
        setupClickListeners();
    }

    private void setupGoogleSignIn() {
        // Configure Google Sign In
        GoogleSignInOptions gso = new GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
                .requestIdToken(getString(R.string.default_web_client_id)) // Generated by google-services plugin
                .requestEmail()
                .build();

        googleSignInClient = GoogleSignIn.getClient(this, gso);
    }

    private void setupClickListeners() {
        binding.btnLogin.setOnClickListener(v -> attemptLogin());

        binding.tvGoToSignUp.setOnClickListener(v -> {
            startActivity(new Intent(this, SignUpActivity.class));
            overridePendingTransition(R.anim.slide_in_right, R.anim.slide_out_left);
        });

        binding.tvForgotPassword.setOnClickListener(v -> showForgotPasswordDialog());

        binding.btnGoogle.setOnClickListener(v -> signInWithGoogle());
    }

    private void signInWithGoogle() {
        Intent signInIntent = googleSignInClient.getSignInIntent();
        startActivityForResult(signInIntent, RC_SIGN_IN);
    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, @Nullable Intent data) {
        super.onActivityResult(requestCode, resultCode, data);

        if (requestCode == RC_SIGN_IN) {
            Task<GoogleSignInAccount> task = GoogleSignIn.getSignedInAccountFromIntent(data);
            try {
                GoogleSignInAccount account = task.getResult(ApiException.class);
                if (account != null) {
                    firebaseAuthWithGoogle(account.getIdToken());
                }
            } catch (ApiException e) {
                Log.w(TAG, "Google sign in failed code: " + e.getStatusCode(), e);
                Snackbar.make(binding.getRoot(), "Google Sign-In failed (Code " + e.getStatusCode() + "): " + e.getMessage(), Snackbar.LENGTH_LONG).show();
            }
        }
    }

    private void firebaseAuthWithGoogle(String idToken) {
        setLoading(true);
        AuthCredential credential = GoogleAuthProvider.getCredential(idToken, null);
        auth.signInWithCredential(credential)
                .addOnSuccessListener(authResult -> {
                    setLoading(false);
                    navigateToMain();
                })
                .addOnFailureListener(e -> {
                    setLoading(false);
                    Log.e(TAG, "Firebase auth with Google failed", e);
                    Snackbar.make(binding.getRoot(), "Firebase Authentication failed: " + e.getLocalizedMessage(), Snackbar.LENGTH_SHORT).show();
                });
    }

    private void attemptLogin() {
        String email    = binding.etEmail.getText().toString().trim();
        String password = binding.etPassword.getText().toString();

        binding.tilEmail.setError(null);
        binding.tilPassword.setError(null);

        boolean valid = true;
        if (!ValidationUtils.isValidEmail(email)) {
            binding.tilEmail.setError(getString(R.string.error_invalid_email));
            valid = false;
        }
        if (password.isEmpty()) {
            binding.tilPassword.setError(getString(R.string.error_empty_field));
            valid = false;
        }
        if (!valid) return;

        setLoading(true);

        auth.signInWithEmailAndPassword(email, password)
                .addOnSuccessListener(authResult -> {
                    setLoading(false);
                    navigateToMain();
                })
                .addOnFailureListener(e -> {
                    setLoading(false);
                    binding.tilPassword.setError("Invalid email or password");
                });
    }

    private void navigateToMain() {
        Intent intent = new Intent(this, MainActivity.class);
        intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK | Intent.FLAG_ACTIVITY_CLEAR_TASK);
        startActivity(intent);
    }

    private void showForgotPasswordDialog() {
        View dialogView = getLayoutInflater().inflate(R.layout.dialog_forgot_password, null);
        new MaterialAlertDialogBuilder(this)
                .setTitle("Reset password")
                .setView(dialogView)
                .setPositiveButton("Send link", (dialog, which) -> {
                    String email = binding.etEmail.getText().toString().trim();
                    if (ValidationUtils.isValidEmail(email)) {
                        auth.sendPasswordResetEmail(email)
                                .addOnSuccessListener(unused ->
                                        Snackbar.make(binding.getRoot(),
                                                "Reset link sent to " + email,
                                                Snackbar.LENGTH_LONG).show())
                                .addOnFailureListener(e ->
                                        Snackbar.make(binding.getRoot(),
                                                "Error: " + e.getMessage(),
                                                Snackbar.LENGTH_LONG).show());
                    } else {
                        binding.tilEmail.setError("Enter your email first");
                    }
                })
                .setNegativeButton("Cancel", null)
                .show();
    }

    private void setLoading(boolean loading) {
        binding.btnLogin.setEnabled(!loading);
        binding.btnGoogle.setEnabled(!loading);
        binding.btnLogin.setText(loading ? getString(R.string.logging_in) : getString(R.string.login));
    }

    private void styleSignUpLink() {
        String full = getString(R.string.no_account);
        SpannableString spannable = new SpannableString(full);
        int start = full.indexOf("Sign up");
        if (start >= 0) {
            int color = ContextCompat.getColor(this, R.color.md_primary);
            spannable.setSpan(new ForegroundColorSpan(color),
                    start, start + 7, Spanned.SPAN_EXCLUSIVE_EXCLUSIVE);
            spannable.setSpan(new UnderlineSpan(),
                    start, start + 7, Spanned.SPAN_EXCLUSIVE_EXCLUSIVE);
        }
        binding.tvGoToSignUp.setText(spannable);
    }
}
